# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-04-23 20:18
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pollyServer', '0005_question_is_transparernt'),
    ]

    operations = [
        migrations.RenameField(
            model_name='question',
            old_name='is_transparernt',
            new_name='is_transparent',
        ),
    ]
