# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-04-23 20:50
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pollyServer', '0006_auto_20170423_2318'),
    ]

    operations = [
        migrations.AlterField(
            model_name='choice',
            name='users_voted',
            field=models.ManyToManyField(blank=True, to=settings.AUTH_USER_MODEL),
        ),
    ]
